Deployment

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,20 +2,21 @@ name: NodeJS Github Action
 
 on:
   push:
-    branches: [main]
+    branches:
+      - main
   pull_request:
-    branches: [main]
+    branches:
+      - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v3 # Checkout the repository
       - name: Use Node
         uses: actions/setup-node@v1
         with:
-          node-version: '16'
-      # Install and Build NodeJS app
+          node-version: 16
       - name: npm install and build
         run: |
           npm install
@@ -23,51 +24,52 @@ jobs:
       - name: Adjust permissions for jest
         run: chmod +x ./node_modules/.bin/jest
 
-      - name: Run Tests
+      - name: npm test
         run: npm test
 
-
-      #- name: Build Node.js Docker Image
-      # run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest -f Dockerfile.app .
-
-      # BUild the NGINX inage
-      - name: Build NGINX image
-        run: docker build -t dapsonic/nginx:latest -f nginx/Dockerfile ./nginx
-
-      - name: List Docker images 
-        run: docker images
-  
+  publish_to_docker:
+    needs: build
+    runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/main' 
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
       - name: Login to DockerHub
-        uses: docker/login-action@v1
+        uses: docker/login-action@v1 
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
-      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops_com619-devops:latest .
-      - run: docker push ${{ secrets.DOCKER_USERNAME }}/devops_com619-devops:latest
-
+      - name: Build and push Docker image
+        run: |
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops_com619-devops:latest .
+          docker push ${{ secrets.DOCKER_USERNAME }}/devops_com619-devops:latest
+      - name: Build and push Docker image for NGINX
+        run: |
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops_com619-nginx:latest  ./nginx
+          docker push ${{ secrets.DOCKER_USERNAME }}/devops_com619-nginx:latest
   deploy:
-    needs: build
+    needs: publish_to_docker
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
       - name: Setup SSH Connection
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          if [ $? -ne 0 ]; then echo "Writing key failed"; exit 1; fi
           chmod 600 ~/.ssh/id_rsa
+          if [ $? -ne 0 ]; then echo "Chmod failed"; exit 1; fi
+          ssh-keyscan -H comdevops.uksouth.cloudapp.azure.com >> ~/.ssh/known_hosts
+          if [ $? -ne 0 ]; then echo "Ssh-keyscan failed"; exit 1; fi
 
+      - name: Check SSH Key Line Count
+        run: wc -l ~/.ssh/id_rsa
 
-
-      #- name: Push NodeJS App Image
-      #  run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
-
-      - name: Re-tag Nginx Image
-        run: |
-          docker tag dapsonic/nginx:latest dapsonic/nginx:latest
-    
-      # Push the Nginx image to Docker Hub
-      - name: Push Nginx Image
-        run: docker push dapsonic/nginx:latest
-    
+      - name: Check SSH Key Character Count
+        run: wc -m ~/.ssh/id_rsa
+        
       - name: Deploy to Azure VM
-        run: ssh -o StrictHostKeyChecking=no com619@comdevops.uksouth.cloudapp.azure.com 'bash -s' < deploy_script.sh
+        run: |
+          scp ./deploy_script.sh com619@comdevops.uksouth.cloudapp.azure.com:/tmp/
+          ssh -o StrictHostKeyChecking=no com619@comdevops.uksouth.cloudapp.azure.com 'bash -s' < deploy_script.sh
